# Vectorized operations

In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(x + 1)

[2 3 4 5]


In [3]:
y = np.array([-1,2,3,0])
print(x*y)

[-1  4  9  0]


In [7]:
np.dot(x,y)

np.int64(12)

In [8]:
x == y

array([False,  True,  True, False])

# Universal functions(ufuncs)

In [16]:
x = np.arange(5,10)
np.square(x)
print(x)
y = np.ones(5) * 10
print(np.mod(y,x))
print(y)
np.minimum(x,7)


[5 6 7 8 9]
[0. 4. 3. 2. 1.]
[10. 10. 10. 10. 10.]


array([5, 6, 7, 7, 7])

In [18]:
# more advanced ufuncs
z = np.repeat(x,3).reshape(-1,3)
print(z)

[[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


In [20]:
np.median(z)

np.float64(7.0)

In [22]:
np.median(z, axis = 0)

array([7., 7., 7.])

In [26]:
np.median(z, axis = 1)

array([5., 6., 7., 8., 9.])

# Broadcasting and shape manipulation

Two conditions for broadcasting:
1. Two arrays should be of equal dimensions
2. One of them is 1

In [33]:
x = np.array([0,10,20]).repeat(3).reshape(-1,3)
print(x)
print(x.shape)

y = np.array([1,2,3])
print(y.shape)
print(x+y)
print(x+y[:, None])
print(x+y[None,:])

[[ 0  0  0]
 [10 10 10]
 [20 20 20]]
(3, 3)
(3,)
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
[[ 1  1  1]
 [12 12 12]
 [23 23 23]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [35]:
x = np.array([[0],[10],[20]])
print(x)
print(x+y)

[[ 0]
 [10]
 [20]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [38]:
x = np.arange(1000000)
x.shape = 100, 100, 100
%timeit x.flatten() # create a new copy of x
%timeit x.ravel() # change the view of x

2.33 ms ± 12.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
101 ns ± 1.58 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [41]:
x = np.arange(0, 10, 2)
y = np.arange(0,-5,-1)
print(np.vstack([x,y]))
print(np.hstack([x,y]))


[[ 0  2  4  6  8]
 [ 0 -1 -2 -3 -4]]
[ 0  2  4  6  8  0 -1 -2 -3 -4]


# A boolean mask

In [42]:
x = np.array([1,3,-1,5,7,-1])
mask = (x<0)
mask

array([False, False,  True, False, False,  True])

In [43]:
x[mask] = 0
x

array([1, 3, 0, 5, 7, 0])

In [48]:
x = np.random.random(50)
(x > .5).sum() # count the number of numbers greater than 0.5 in the random array

np.int64(24)

# Helper function

In [52]:
np.resize?

Signature:       np.resize(a, new_shape)
Call signature:  np.resize(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function resize at 0x0000019278CFBB00>
File:            c:\users\xwx\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return a new array with the specified shape.

If the new array is larger than the original array, then the new
array is filled with repeated copies of `a`.  Note that this behavior
is different from a.resize(new_shape) which fills with zeros instead
of repeated copies of `a`.

Parameters
----------
a : array_like
    Array to be resized.

new_shape : int or tuple of int
    Shape of resized array.

Returns
-------
reshaped_array : ndarray
    The new array is formed from the data in the old array, repeated
    if necessary to fill out the required number of elements.  The
    data are repeated iterating over the array in C-order.

See Also
--------
numpy.reshape : Reshape an array without changing the tot

In [54]:
help(np.resize)

Help on _ArrayFunctionDispatcher in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.

    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.

    Parameters
    ----------
    a : array_like
        Array to be resized.

    new_shape : int or tuple of int
        Shape of resized array.

    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated iterating over the array in C-order.

    See Also
    --------
    numpy.reshape : Reshape an array without changing the total size.
    numpy.pad : Enlarge and pad an array.
    numpy.repeat : Repeat elements of an array.
    ndarray.resize : resize an arra

In [55]:
dir(np.resize)

['__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__type_params__',
 '__wrapped__',
 '_implementation']